# Generated by Django 6.0.2 on 2026-02-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0003_endorsementquota_endorsement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('member_dispute', 'Member Dispute'), ('endorsement_fraud', 'Endorsement Fraud'), ('election_challenge', 'Election Challenge'), ('other', 'Other')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('decided', 'Decided'), ('appealed', 'Appealed'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=list, help_text='List of evidence items: [{"type": "text"|"file_url", "content": "..."}]')),
                ('tier', models.IntegerField(choices=[(50, '50s Leader'), (100, '100s Leader'), (1000, '1000s Leader (Council)')], help_text='Governance tier responsible for adjudicating this case')),
                ('decision_text', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arbitrator', models.ForeignKey(blank=True, help_text='Leader assigned to adjudicate this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitration_cases', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_complaints', to=settings.AUTH_USER_MODEL)),
                ('related_endorsement', models.ForeignKey(blank=True, help_text='Relevant endorsement (for endorsement_fraud cases)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitration_cases', to='communities.endorsement')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitration_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arbitration Case',
                'verbose_name_plural': 'Arbitration Cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['complainant', 'created_at'], name='arbitration_complai_f42284_idx'), models.Index(fields=['arbitrator', 'status'], name='arbitration_arbitra_f5c5d8_idx'), models.Index(fields=['status', 'tier'], name='arbitration_status_9ba14d_idx')],
            },
        ),
    ]
