# Generated by Django 6.0.2 on 2026-02-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupoften',
            new_name='communities_precinc_b5bef9_idx',
            old_name='communities_precin_4c8b3f_idx',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='communities_group_i_6a2825_idx',
            old_name='communities_group_i_13f8a2_idx',
        ),
    ]
