# Generated by Django 6.0.2 on 2026-02-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_rename_communities_precin_4c8b3f_idx_communities_precinc_b5bef9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorsementQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_slots', models.PositiveSmallIntegerField(default=10, help_text='Maximum number of endorsements allowed')),
                ('used_slots', models.PositiveSmallIntegerField(default=0, help_text='Number of active endorsements')),
                ('is_suspended', models.BooleanField(default=False, help_text='Penalty: cannot endorse if suspended')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_reason', models.TextField(blank=True)),
                ('geder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endorsement Quota',
                'verbose_name_plural': 'Endorsement Quotas',
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('penalized', 'Penalized')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('guarantor', models.ForeignKey(help_text='GeDer who vouches for the supporter', on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('supporter', models.OneToOneField(help_text='User being endorsed', on_delete=django.db.models.deletion.CASCADE, related_name='endorsement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guarantor', 'status'], name='communities_guarant_870977_idx')],
            },
        ),
    ]
