# Generated by Django 6.0.2 on 2026-02-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0003_endorsementquota_endorsement'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('atistavi', 'Atistavi Election'), ('hierarchy', 'Hierarchy Election'), ('parliamentary', 'Parliamentary Election')], db_index=True, help_text='Type of election', max_length=20)),
                ('status', models.CharField(choices=[('nomination', 'Nomination Period'), ('voting', 'Voting Period'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='nomination', help_text='Current election status', max_length=20)),
                ('nomination_start', models.DateTimeField(help_text='When nomination period starts')),
                ('nomination_end', models.DateTimeField(help_text='When nomination period ends')),
                ('voting_start', models.DateTimeField(help_text='When voting period starts')),
                ('voting_end', models.DateTimeField(help_text='When voting period ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this election', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, help_text="Candidate's statement (optional)")),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether candidacy is approved (for future moderation)')),
                ('candidate', models.ForeignKey(help_text='User running as candidate', on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(help_text='Election this candidacy is for', on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='governance.election')),
            ],
            options={
                'verbose_name': 'Candidacy',
                'verbose_name_plural': 'Candidacies',
                'ordering': ['registered_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(10, 'Atistavi (10s Leader)'), (50, '50s Leader'), (100, '100s Leader'), (1000, '1000s Leader (Council Member)')], db_index=True, help_text='Leadership tier in the hierarchy')),
                ('held_since', models.DateTimeField(blank=True, help_text='When the current holder assumed this position', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this position is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, help_text='District (for tier >= 100)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='territories.district')),
                ('group', models.OneToOneField(blank=True, help_text='Group of ten (for tier=10 only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='communities.groupoften')),
                ('holder', models.ForeignKey(blank=True, help_text='Current leader holding this position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_positions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent position in the hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='governance.leaderposition')),
                ('precinct', models.ForeignKey(blank=True, help_text='Precinct (for tier >= 50)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='territories.precinct')),
            ],
            options={
                'verbose_name': 'Leader Position',
                'verbose_name_plural': 'Leader Positions',
                'ordering': ['tier', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='election',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position being elected (null for parliamentary elections)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='governance.leaderposition'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('candidacy', models.ForeignKey(help_text='Candidacy receiving this vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.candidacy')),
                ('election', models.ForeignKey(help_text='Election this vote is for', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.election')),
                ('voter', models.ForeignKey(help_text='User who cast this vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-cast_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidacy',
            index=models.Index(fields=['election', 'is_approved'], name='governance__electio_285e2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(fields=('election', 'candidate'), name='unique_candidacy_per_user_per_election'),
        ),
        migrations.AddIndex(
            model_name='leaderposition',
            index=models.Index(fields=['tier', 'is_active'], name='governance__tier_6f12d9_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderposition',
            index=models.Index(fields=['precinct', 'tier'], name='governance__precinc_851e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderposition',
            index=models.Index(fields=['district', 'tier'], name='governance__distric_173092_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status', 'election_type'], name='governance__status_f2de4c_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidacy'], name='governance__candida_ba4216_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('election', 'voter'), name='one_vote_per_user_per_election'),
        ),
    ]
