# Generated by Django 6.0.2 on 2026-02-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('threshold_met', 'Threshold Met'), ('responded', 'Responded'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('signature_threshold', models.PositiveIntegerField(default=10, help_text='Number of signatures required to meet the threshold')),
                ('response_text', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='territories.district')),
                ('precinct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='territories.precinct')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='initiatives.initiative')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Initiative Signature',
                'verbose_name_plural': 'Initiative Signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['status', 'precinct'], name='initiatives_status_970ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['author', 'created_at'], name='initiatives_author__ce4243_idx'),
        ),
        migrations.AddIndex(
            model_name='initiativesignature',
            index=models.Index(fields=['initiative', 'signed_at'], name='initiatives_initiat_1725e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='initiativesignature',
            constraint=models.UniqueConstraint(fields=('initiative', 'signer'), name='unique_signature_per_user_per_initiative'),
        ),
    ]
