# Generated by Django 6.0.2 on 2026-02-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('escalation_level', models.IntegerField(choices=[(10, 'Atistavi (Group Leader)'), (50, '50s Leader'), (100, '100s Leader'), (1000, '1000s Leader (Council)'), (9999, 'Media')], db_index=True, default=10, help_text='Current escalation level (which governance tier is handling this)')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('moral_filter_answer', models.TextField(help_text="Reporter's answer to the moral filter question")),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Leader currently handling this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who submitted the SOS report', on_delete=django.db.models.deletion.CASCADE, related_name='sos_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Report',
                'verbose_name_plural': 'SOS Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.IntegerField(choices=[(10, 'Atistavi (Group Leader)'), (50, '50s Leader'), (100, '100s Leader'), (1000, '1000s Leader (Council)'), (9999, 'Media')])),
                ('to_level', models.IntegerField(choices=[(10, 'Atistavi (Group Leader)'), (50, '50s Leader'), (100, '100s Leader'), (1000, '1000s Leader (Council)'), (9999, 'Media')])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escalated_by', models.ForeignKey(blank=True, help_text='User who escalated. Null = auto-escalated by system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_escalations_performed', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='sos.sosreport')),
            ],
            options={
                'verbose_name': 'SOS Escalation',
                'verbose_name_plural': 'SOS Escalations',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sosreport',
            index=models.Index(fields=['assigned_to', 'status'], name='sos_sosrepo_assigne_4973b8_idx'),
        ),
        migrations.AddIndex(
            model_name='sosreport',
            index=models.Index(fields=['reporter', 'created_at'], name='sos_sosrepo_reporte_9dbb80_idx'),
        ),
        migrations.AddIndex(
            model_name='sosreport',
            index=models.Index(fields=['escalation_level'], name='sos_sosrepo_escalat_3a362e_idx'),
        ),
    ]
