# Generated by Django 6.0.2 on 2026-02-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='precinct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='territories.precinct'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['precinct', 'role'], name='accounts_us_precinc_4d2098_idx'),
        ),
    ]
