# Generated by Django 6.0.2 on 2026-03-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_user_id_a4ff2e_idx',
            old_name='accounts_no_user_id_is_read_idx',
        ),
    ]
